[2022-10-01 19:45:32,409] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.store_company_dim_table manual__2022-10-01T19:44:19.977775+00:00 [queued]>
[2022-10-01 19:45:32,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: main_dag.store_company_dim_table manual__2022-10-01T19:44:19.977775+00:00 [queued]>
[2022-10-01 19:45:32,424] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:45:32,425] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-01 19:45:32,425] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-01 19:45:32,446] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): store_company_dim_table> on 2022-10-01 19:44:19.977775+00:00
[2022-10-01 19:45:32,452] {standard_task_runner.py:52} INFO - Started process 410 to run task
[2022-10-01 19:45:32,457] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'store_company_dim_table', 'manual__2022-10-01T19:44:19.977775+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpzz5ena5d', '--error-file', '/tmp/tmpc2kh48r5']
[2022-10-01 19:45:32,459] {standard_task_runner.py:80} INFO - Job 56: Subtask store_company_dim_table
[2022-10-01 19:45:32,533] {task_command.py:369} INFO - Running <TaskInstance: main_dag.store_company_dim_table manual__2022-10-01T19:44:19.977775+00:00 [running]> on host cb37a969dddb
[2022-10-01 19:45:32,641] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=store_company_dim_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-01T19:44:19.977775+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-01T19:44:19.977775+00:00
[2022-10-01 19:45:32,643] {postgres.py:127} INFO - Running copy expert: COPY company_dim_table FROM stdin WITH DELIMITER as ',', filename: df_company_dim_table.csv
[2022-10-01 19:45:32,712] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-10-01 19:45:32,730] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main_dag.py", line 28, in store_company_dim_table
    filename = 'df_company_dim_table.csv'
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 135, in copy_expert
    cur.copy_expert(sql, file)
psycopg2.errors.BadCopyFileFormat: missing data for column "company_key"
CONTEXT:  COPY company_dim_table, line 1: "LEAPONETECH SOLUTIONS HOLDINGS BERHAD,No,Software,1599"

[2022-10-01 19:45:32,761] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=main_dag, task_id=store_company_dim_table, execution_date=20221001T194419, start_date=20221001T194532, end_date=20221001T194532
[2022-10-01 19:45:32,783] {standard_task_runner.py:97} ERROR - Failed to execute job 56 for task store_company_dim_table (missing data for column "company_key"
CONTEXT:  COPY company_dim_table, line 1: "LEAPONETECH SOLUTIONS HOLDINGS BERHAD,No,Software,1599"
; 410)
[2022-10-01 19:45:32,833] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-01 19:45:32,934] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
